[project]
protostar-version = "0.7.0"
lib-path = "src"
cairo_path = ["src"]

[profile.unit.test]
target = ["src/stark_verifier/crypto"]
cairo-path = ["src"]

[profile.integration.test]
target = ["tests"]
cairo-path = ["src"]
